import { StyleSheet } from "react-native";
import { V2 } from "@/components/v2/tokens";

export const styles = StyleSheet.create({
  section: { gap: 12 },
  sectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
  },
  sectionHeadingMobile: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 10,
  },
  headingCopy: { flex: 1, minWidth: 0, gap: 3 },
  eyebrow: { color: V2.gold, fontSize: 9, fontWeight: "900" },
  title: { color: V2.text, fontSize: 22, lineHeight: 28, fontWeight: "900" },
  titleMobile: { fontSize: 20, lineHeight: 26 },
  subtitle: { color: V2.textMuted, fontSize: 10, lineHeight: 15 },
  formulaBadge: {
    minWidth: 280,
    paddingLeft: 14,
    borderLeftWidth: 2,
    borderLeftColor: V2.gold,
    gap: 2,
  },
  formulaLabel: { color: V2.textDim, fontSize: 9, fontWeight: "800" },
  formulaText: {
    color: V2.text,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "900",
  },
  formulaRail: {
    minHeight: 54,
    flexDirection: "row",
    flexWrap: "wrap",
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 6,
    backgroundColor: V2.backgroundRaised,
  },
  formulaStep: {
    minWidth: 130,
    flex: 1,
    paddingHorizontal: 11,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRightWidth: 1,
    borderRightColor: V2.border,
  },
  formulaIndex: { color: V2.gold, fontSize: 10, fontWeight: "900" },
  formulaStepCopy: { flex: 1, minWidth: 0, gap: 3 },
  formulaStepLabel: { color: V2.textDim, fontSize: 9 },
  formulaStepValue: { color: V2.text, fontSize: 11, fontWeight: "900" },
  configurator: {
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 6,
    backgroundColor: V2.backgroundRaised,
    flexDirection: "row",
    alignItems: "stretch",
    overflow: "hidden",
  },
  configuratorNarrow: { flexDirection: "column" },
  controls: { flex: 1, minWidth: 0, paddingHorizontal: 14 },
  step: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: V2.border,
  },
  stepLast: { borderBottomWidth: 0 },
  stepHeading: { flexDirection: "row", alignItems: "flex-start", gap: 9 },
  stepIndex: {
    width: 22,
    paddingTop: 2,
    color: V2.textDim,
    fontSize: 9,
    fontWeight: "900",
  },
  stepHeadingCopy: { flex: 1, minWidth: 0, gap: 3 },
  stepTitle: {
    color: V2.text,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  stepDetail: { color: V2.textMuted, fontSize: 10, lineHeight: 15 },
  stepBody: { marginTop: 10 },
  capitalRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  stackRow: { flexDirection: "column", alignItems: "stretch" },
  moneyInput: {
    width: 220,
    minHeight: 42,
    borderWidth: 1,
    borderColor: V2.borderStrong,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
  },
  moneyInputFocused: { borderColor: V2.gold },
  moneyPrefix: {
    paddingLeft: 11,
    color: V2.gold,
    fontSize: 15,
    fontWeight: "900",
  },
  input: {
    flex: 1,
    height: 40,
    paddingHorizontal: 8,
    color: V2.text,
    fontSize: 15,
    fontWeight: "900",
    outlineStyle: "none",
  } as any,
  currency: {
    paddingRight: 11,
    color: V2.textMuted,
    fontSize: 9,
    fontWeight: "900",
  },
  presetRow: { flex: 1, flexDirection: "row", flexWrap: "wrap", gap: 6 },
  presetButton: {
    minWidth: 62,
    minHeight: 36,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  presetButtonActive: {
    borderColor: V2.gold,
    backgroundColor: "rgba(216,188,131,0.08)",
  },
  presetText: { color: V2.textMuted, fontSize: 10, fontWeight: "800" },
  presetTextActive: { color: V2.gold },
  riskOptions: { flexDirection: "row", gap: 8 },
  riskOption: {
    flex: 1,
    minWidth: 150,
    padding: 11,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 5,
    gap: 5,
    backgroundColor: V2.surfaceMuted,
  },
  optionActive: {
    borderColor: "rgba(216,188,131,0.68)",
    backgroundColor: "rgba(216,188,131,0.06)",
  },
  optionTitleRow: { flexDirection: "row", alignItems: "center", gap: 7 },
  optionTitle: { color: V2.text, fontSize: 12, fontWeight: "900" },
  optionTitleActive: { color: V2.gold },
  optionValue: {
    marginLeft: "auto",
    color: V2.amber,
    fontSize: 11,
    fontWeight: "900",
  },
  optionDetail: {
    paddingLeft: 24,
    color: V2.textMuted,
    fontSize: 9,
    lineHeight: 13,
  },
  strategyOptions: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  strategyOption: {
    width: "32.5%",
    minWidth: 190,
    minHeight: 48,
    paddingHorizontal: 9,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: V2.surfaceMuted,
  },
  strategyRail: { width: 3, height: 25 },
  strategyOptionCopy: { flex: 1, minWidth: 0, gap: 2 },
  strategyName: { color: V2.text, fontSize: 11, fontWeight: "900" },
  strategyMeta: { color: V2.textMuted, fontSize: 8 },
  platformOptions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  platformOption: {
    flex: 1,
    minWidth: 220,
    padding: 11,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 5,
    gap: 9,
    backgroundColor: V2.surfaceMuted,
  },
  platformTopline: { flexDirection: "row", alignItems: "center", gap: 8 },
  platformCode: {
    width: 34,
    height: 34,
    borderWidth: 1,
    borderColor: V2.borderStrong,
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  platformCodeText: { color: V2.gold, fontSize: 9, fontWeight: "900" },
  platformTitleCopy: { flex: 1, minWidth: 0, gap: 1 },
  platformName: { color: V2.text, fontSize: 11, fontWeight: "900" },
  platformAccount: { color: V2.textMuted, fontSize: 8 },
  platformFacts: {
    gap: 3,
    paddingTop: 7,
    borderTopWidth: 1,
    borderTopColor: V2.border,
  },
  platformFact: { color: V2.textMuted, fontSize: 8, lineHeight: 12 },
  modeOptions: { flexDirection: "row", gap: 9 },
  modeOption: {
    flex: 1,
    minWidth: 250,
    padding: 13,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 5,
    gap: 8,
    backgroundColor: V2.surfaceMuted,
  },
  modeTopline: { flexDirection: "row", alignItems: "center", gap: 8 },
  modeTitle: { color: V2.text, fontSize: 13, fontWeight: "900" },
  modeBadge: {
    marginLeft: "auto",
    minHeight: 22,
    paddingHorizontal: 7,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 3,
    justifyContent: "center",
  },
  modeBadgeActive: {
    borderColor: "rgba(216,188,131,0.5)",
    backgroundColor: "rgba(216,188,131,0.08)",
  },
  modeBadgeText: { color: V2.textMuted, fontSize: 8, fontWeight: "800" },
  modeBadgeTextActive: { color: V2.gold },
  modeDetail: { color: V2.textMuted, fontSize: 10, lineHeight: 16 },
  summary: {
    width: 370,
    flexShrink: 0,
    padding: 18,
    borderLeftWidth: 1,
    borderLeftColor: V2.border,
    backgroundColor: V2.surfaceMuted,
    gap: 15,
  },
  summaryNarrow: {
    width: "100%",
    borderLeftWidth: 0,
    borderTopWidth: 1,
    borderTopColor: V2.border,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryEyebrow: { color: V2.gold, fontSize: 9, fontWeight: "900" },
  summaryTitle: {
    marginTop: 3,
    color: V2.text,
    fontSize: 20,
    fontWeight: "900",
  },
  completion: { alignItems: "flex-end", gap: 1 },
  completionValue: { color: V2.green, fontSize: 18, fontWeight: "900" },
  completionLabel: { color: V2.textDim, fontSize: 8 },
  fundPath: {
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(66,211,161,0.34)",
    borderRadius: 4,
    backgroundColor: "rgba(66,211,161,0.05)",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  fundPathManaged: {
    borderColor: "rgba(216,188,131,0.4)",
    backgroundColor: "rgba(216,188,131,0.06)",
  },
  fundPathCopy: { flex: 1, gap: 3 },
  fundPathTitle: { color: V2.text, fontSize: 12, fontWeight: "900" },
  fundPathDetail: { color: V2.textMuted, fontSize: 9, lineHeight: 14 },
  summaryRows: { borderTopWidth: 1, borderTopColor: V2.border },
  summaryRow: {
    minHeight: 45,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: V2.border,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  summaryLabel: { width: 72, color: V2.textDim, fontSize: 9, lineHeight: 14 },
  summaryValue: {
    flex: 1,
    color: V2.text,
    fontSize: 10,
    lineHeight: 15,
    fontWeight: "800",
    textAlign: "right",
  },
  issue: {
    padding: 10,
    borderWidth: 1,
    borderColor: "rgba(231,183,95,0.35)",
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  issueText: { flex: 1, color: V2.amber, fontSize: 9, lineHeight: 14 },
  ready: { minHeight: 34, flexDirection: "row", alignItems: "center", gap: 7 },
  readyText: { color: V2.green, fontSize: 10, fontWeight: "800" },
  generated: {
    padding: 11,
    borderWidth: 1,
    borderColor: "rgba(66,211,161,0.3)",
    borderRadius: 4,
    gap: 3,
    backgroundColor: "rgba(66,211,161,0.04)",
  },
  generatedTopline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  generatedTitle: { color: V2.text, fontSize: 11, fontWeight: "900" },
  generatedStatus: { color: V2.green, fontSize: 8, fontWeight: "900" },
  generatedMeta: {
    marginTop: 6,
    color: V2.textMuted,
    fontSize: 8,
    lineHeight: 12,
  },
  staleText: { color: V2.amber, fontSize: 9, lineHeight: 14 },
  generateButton: {
    minHeight: 44,
    borderRadius: 4,
    backgroundColor: V2.gold,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  generateButtonDisabled: { opacity: 0.38 },
  generateText: { color: V2.background, fontSize: 11, fontWeight: "900" },
  advancedButton: {
    minHeight: 40,
    borderWidth: 1,
    borderColor: V2.borderStrong,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  advancedText: { color: V2.text, fontSize: 10, fontWeight: "800" },
  disclaimer: {
    color: V2.textDim,
    fontSize: 8,
    lineHeight: 13,
    textAlign: "center",
  },
  disabled: { opacity: 0.38 },
  pressed: { opacity: 0.72 },
});
