import type { PromoCategory, PromoProduct } from "./types";

export const PROMO_CATEGORIES: PromoCategory[] = [
  { key: "", label: "全部精选", icon: "diamond" },
  { key: "ea", label: "EA策略", icon: "trending-up" },
  { key: "indicator", label: "指标工具", icon: "analytics" },
  { key: "tool", label: "辅助工具", icon: "construct" },
  { key: "course", label: "实战教程", icon: "book" },
];

export const PROMO_ANNOUNCEMENTS = [
  "EA 商品与资管入金使用独立 USDT 对账记录",
  "商品价格、库存、交付内容以当次订单为准",
  "源码来源与商业授权须在购买前逐项核验",
  "历史、模拟或回测数据不代表未来表现",
];

export const PLACEHOLDER_PROMO_PRODUCTS: PromoProduct[] = [
  {
    id: -1,
    title: "Gold Scalper Pro 2026",
    description: "纽约时段黄金剥头皮结构 · 点差与滑点敏感 · 证据待核验",
    platform: "MT5",
    category: "ea",
    originalPrice: "599",
    promoPrice: "199",
    promoLabel: "限时3折",
    promoEndTime: "2026-05-01 00:00:00",
    stock: 20,
    soldCount: 14,
    detailContent:
      "Gold Scalper Pro 是纽约时段黄金剥头皮策略的演示商品。高频策略对点差、滑点、延迟和券商执行高度敏感。\n\n核验要求：\n• 数据是否为真实账户\n• 时间区间、入出金与未平仓口径\n• 最大回撤与极端行情表现\n• 历史数据不代表未来结果",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "待核验", profit: "待核验", drawdown: "待核验", trades: "待核验" },
  },
  {
    id: -2,
    title: "Multi-Pair Hedge System",
    description: "多品种对冲结构 · 相关性可失效 · 收益与回撤证据待核验",
    platform: "MT4",
    category: "ea",
    originalPrice: "1299",
    promoPrice: "499",
    promoLabel: "爆款直降",
    promoEndTime: "2026-04-30 00:00:00",
    stock: 15,
    soldCount: 9,
    detailContent: "Multi-Pair Hedge System 是多品种对冲结构的演示商品。历史相关性和价差回归可能失效，多品种同时开仓也会放大执行、隔夜和保证金风险。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "待核验", profit: "待核验", drawdown: "待核验", trades: "待核验" },
  },
  {
    id: -3,
    title: "Trend Rider EA",
    description: "多时间框架趋势追踪 · H4+M15 确认 · 震荡市可能连续止损",
    platform: "MT5",
    category: "ea",
    originalPrice: "899",
    promoPrice: "349",
    promoLabel: "新品首发",
    promoEndTime: "2026-05-15 00:00:00",
    stock: 30,
    soldCount: 7,
    detailContent: "Trend Rider EA 使用多时间框架趋势条件与动态止损。趋势判断可能滞后，在震荡市中也可能反复止损，需查看样本外结果。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "待核验", profit: "待核验", drawdown: "待核验", trades: "待核验" },
  },
  {
    id: -4,
    title: "Smart Grid Pro",
    description: "自适应网格交易 · ATR 动态间距 · 单边行情高风险",
    platform: "MT4",
    category: "ea",
    originalPrice: "799",
    promoPrice: "299",
    promoLabel: "热卖中",
    promoEndTime: "2026-06-01 00:00:00",
    stock: 25,
    soldCount: 18,
    detailContent: "Smart Grid Pro 采用 ATR 调整网格间距。网格与加仓逻辑在持续单边行情中可能快速放大仓位、保证金和爆仓风险。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "待核验", profit: "待核验", drawdown: "待核验", trades: "待核验" },
  },
  {
    id: -5,
    title: "Order Flow Indicator",
    description: "订单流视觉化工具 · 数据源与延迟需核验 · 不构成交易信号承诺",
    platform: "MT5",
    category: "indicator",
    originalPrice: "399",
    promoPrice: "149",
    promoLabel: "证据待核验",
    promoEndTime: "2026-05-20 00:00:00",
    stock: 50,
    soldCount: 23,
    detailContent: "Order Flow Indicator 尝试展示订单流与流动性视图。数据覆盖、延迟和算法口径会影响结果，不应把图形本身视为收益保证。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "-", profit: "-", drawdown: "-", trades: "-" },
  },
  {
    id: -6,
    title: "Risk Manager Pro",
    description: "风控辅助工具 · 监控回撤与阈值 · 不能消除滑点或极端行情风险",
    platform: "MT4",
    category: "tool",
    originalPrice: "199",
    promoPrice: "79",
    promoLabel: "风控辅助",
    promoEndTime: "2026-07-01 00:00:00",
    stock: 100,
    soldCount: 45,
    detailContent: "Risk Manager Pro 用于监控账户回撤、单笔亏损和日亏损阈值。自动平仓仍可受断网、滑点、跳空和券商执行影响，不承诺保本。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "-", profit: "-", drawdown: "-", trades: "-" },
  },
];
