import type { PromoCategory, PromoProduct } from "./types";

export const PROMO_CATEGORIES: PromoCategory[] = [
  { key: "", label: "🔥 全部精选", icon: "diamond" },
  { key: "ea", label: "EA策略", icon: "trending-up" },
  { key: "indicator", label: "指标工具", icon: "analytics" },
  { key: "tool", label: "辅助工具", icon: "construct" },
  { key: "course", label: "实战教程", icon: "book" },
];

export const PROMO_ANNOUNCEMENTS = [
  "🔥 Gold Scalper Pro 限时3折，仅剩6份",
  "⚡ 新品 Trend Rider EA 首发特惠",
  "💎 全网EA源码直供，价格低至1折",
  "🛡️ 正版授权 · 终身售后 · 源头直供",
];

export const PLACEHOLDER_PROMO_PRODUCTS: PromoProduct[] = [
  {
    id: -1,
    title: "Gold Scalper Pro 2026",
    description: "纽约时段黄金剥头皮EA · 3年实盘验证 · 年化120%+ · 最大回撤8.2%",
    platform: "MT5",
    category: "ea",
    originalPrice: "599",
    promoPrice: "199",
    promoLabel: "限时3折",
    promoEndTime: "2026-05-01 00:00:00",
    stock: 20,
    soldCount: 14,
    detailContent:
      "Gold Scalper Pro 是一款专注于纽约时段的黄金剥头皮策略。采用多重过滤机制，结合波动率自适应算法，在低点差环境下实现稳定盈利。\n\n核心优势：\n• 3年实盘验证，年化收益120%+\n• 最大回撤仅8.2%\n• 自适应点差过滤\n• 内置资金管理模块",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "78%", profit: "120%", drawdown: "8.2%", trades: "3,200+" },
  },
  {
    id: -2,
    title: "Multi-Pair Hedge System",
    description: "28货币对冲套利 · 统计套利算法 · 适合$5000+账户 · 稳定月化5-8%",
    platform: "MT4",
    category: "ea",
    originalPrice: "1299",
    promoPrice: "499",
    promoLabel: "爆款直降",
    promoEndTime: "2026-04-30 00:00:00",
    stock: 15,
    soldCount: 9,
    detailContent: "Multi-Pair Hedge System 是一款专业级多货币对冲系统。同时监控28个主要货币对的价差关系，当价差偏离历史均值时自动建仓，等待价差回归获利。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "85%", profit: "72%", drawdown: "12%", trades: "1,800+" },
  },
  {
    id: -3,
    title: "Trend Rider EA",
    description: "多时间框架趋势追踪 · H4+M15双重确认 · 动态止损 · 单边行情利润最大化",
    platform: "MT5",
    category: "ea",
    originalPrice: "899",
    promoPrice: "349",
    promoLabel: "新品首发",
    promoEndTime: "2026-05-15 00:00:00",
    stock: 30,
    soldCount: 7,
    detailContent: "Trend Rider EA 采用多时间框架趋势分析技术，在H4确认趋势方向后，在M15寻找最佳入场点。配合动态止损和移动止盈，最大化单边行情利润。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "62%", profit: "180%", drawdown: "15%", trades: "960+" },
  },
  {
    id: -4,
    title: "Smart Grid Pro",
    description: "自适应网格交易 · ATR动态间距 · 震荡行情稳定收割 · 自动风控",
    platform: "MT4",
    category: "ea",
    originalPrice: "799",
    promoPrice: "299",
    promoLabel: "热卖中",
    promoEndTime: "2026-06-01 00:00:00",
    stock: 25,
    soldCount: 18,
    detailContent: "Smart Grid Pro 采用自适应网格间距算法，根据ATR动态调整网格密度。在震荡行情中稳定收割利润，遇到单边行情自动收缩仓位控制风险。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "91%", profit: "96%", drawdown: "18%", trades: "5,400+" },
  },
  {
    id: -5,
    title: "Order Flow Indicator",
    description: "机构级订单流指标 · 大单方向实时解析 · 关键价位标注 · 流动性分布",
    platform: "MT5",
    category: "indicator",
    originalPrice: "399",
    promoPrice: "149",
    promoLabel: "独家",
    promoEndTime: "2026-05-20 00:00:00",
    stock: 50,
    soldCount: 23,
    detailContent: "Order Flow Indicator 是一款机构级订单流分析指标，实时解析市场微观结构，显示大单进出方向、关键支撑阻力位和流动性分布。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "-", profit: "-", drawdown: "-", trades: "-" },
  },
  {
    id: -6,
    title: "Risk Manager Pro",
    description: "专业风控工具 · 自动监控回撤 · 超限自动平仓 · 每个交易者必备",
    platform: "MT4",
    category: "tool",
    originalPrice: "199",
    promoPrice: "79",
    promoLabel: "必备工具",
    promoEndTime: "2026-07-01 00:00:00",
    stock: 100,
    soldCount: 45,
    detailContent: "Risk Manager Pro 是每个交易者必备的风控工具。实时监控账户回撤、单笔亏损、日亏损上限等指标，超过预设阈值自动平仓，保护您的本金安全。",
    coverImage: null,
    galleryImages: null,
    paymentInfo: null,
    contactInfo: null,
    status: "active",
    metrics: { winRate: "-", profit: "-", drawdown: "-", trades: "-" },
  },
];
