import { StyleSheet } from "react-native";

type PromoStyleOptions = {
  screenWidth: number;
  isDesktop: boolean;
  cardWidth: number | string;
};

export function createPromoStyles({ screenWidth, isDesktop, cardWidth }: PromoStyleOptions) {
  return StyleSheet.create({
    page: { flex: 1, backgroundColor: "#0A1628" },
    loadingWrap: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#0A1628" },
    backBtn: { position: "absolute", top: 16, left: 16, zIndex: 10, padding: 8, backgroundColor: "rgba(15,23,42,0.8)", borderRadius: 20, borderWidth: 1, borderColor: "#475569" },

    hero: { paddingTop: 70, paddingBottom: 28, paddingHorizontal: 20, alignItems: "center" },
    announcementBar: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(220,38,38,0.15)", paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, gap: 8, marginBottom: 24, borderWidth: 1, borderColor: "rgba(220,38,38,0.3)", maxWidth: 500, width: "100%" },
    announceLive: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#DC2626", paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
    liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#fff" },
    liveText: { color: "#fff", fontSize: 10, fontWeight: "900" },
    announceText: { color: "#FCA5A5", fontSize: 12, fontWeight: "600", flex: 1 },
    heroTitle: { color: "#FFFFFF", fontSize: isDesktop ? 38 : 30, fontWeight: "900", textAlign: "center", letterSpacing: 2 },
    heroTitleLine: { width: 60, height: 3, backgroundColor: "#A8895A", borderRadius: 2, marginVertical: 12 },
    heroSubtitle: { color: "#A8895A", fontSize: 13, fontWeight: "700", letterSpacing: isDesktop ? 6 : 3, marginBottom: 16, textAlign: "center" },
    heroDesc: { color: "#F1F5F9", fontSize: 13, lineHeight: 22, textAlign: "center", marginBottom: 20, maxWidth: 440 },
    heroStats: { flexDirection: "row", gap: 4, marginBottom: 16, width: "100%", maxWidth: 500 },
    heroStatItem: { flex: 1, alignItems: "center", backgroundColor: "#1E293B", paddingVertical: 12, borderRadius: 10, borderWidth: 1, borderColor: "#475569", gap: 4 },
    heroStatNum: { color: "#FFFFFF", fontSize: isDesktop ? 18 : 16, fontWeight: "900" },
    heroStatLabel: { color: "#F1F5F9", fontSize: 10 },
    authorityStrip: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 8 },
    authorityTag: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "rgba(217,119,6,0.1)", paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, borderWidth: 1, borderColor: "rgba(217,119,6,0.2)" },
    authorityTagText: { color: "#A8895A", fontSize: 11, fontWeight: "700" },

    categorySection: { paddingVertical: 14, backgroundColor: "#0A1628", borderBottomWidth: 1, borderBottomColor: "#1E293B" },
    categoryScroll: { paddingHorizontal: 16, gap: 8 },
    categoryChip: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 24, backgroundColor: "#1E293B", borderWidth: 1, borderColor: "#475569" },
    categoryChipActive: { backgroundColor: "#A8895A", borderColor: "#A8895A" },
    categoryChipText: { color: "#F1F5F9", fontSize: 13, fontWeight: "600" },
    categoryChipTextActive: { color: "#0A1628", fontWeight: "800" },
    resultBar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 20, paddingVertical: 14, gap: 12 },
    resultCountRow: { flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 0 },
    resultCount: { color: "#F1F5F9", fontSize: 13 },
    resultCountNum: { color: "#A8895A", fontSize: 14, fontWeight: "900" },
    resultTip: { flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 1 },
    resultTipText: { color: "#10B981", fontSize: 12, fontWeight: "700" },

    productList: { paddingHorizontal: 20, gap: 16, ...(isDesktop ? { flexDirection: "row" as any, flexWrap: "wrap" as any, justifyContent: "center" as any } : {}) },
    productCard: { width: cardWidth as any, backgroundColor: "#1E293B", borderRadius: 16, overflow: "hidden", borderWidth: 1, borderColor: "rgba(148,163,184,0.12)" },
    cardHeader: { padding: 16, position: "relative" },
    discountBadge: { position: "absolute", top: 0, right: 0, backgroundColor: "#DC2626", paddingHorizontal: 14, paddingVertical: 8, borderBottomLeftRadius: 16, zIndex: 2 },
    discountBadgeText: { color: "#fff", fontSize: 16, fontWeight: "900" },
    promoLabel: { position: "absolute", top: 12, left: 12, flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, zIndex: 2 },
    promoLabelText: { color: "#fff", fontSize: 11, fontWeight: "800" },
    cardHeaderContent: { flexDirection: "row", alignItems: "center", gap: 14, marginTop: 20, marginBottom: 14 },
    cardCoverImage: { width: 64, height: 64, borderRadius: 12 },
    cardIconWrap: { width: 64, height: 64, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.1)", justifyContent: "center", alignItems: "center" },
    cardHeaderInfo: { flex: 1, minWidth: 0 },
    cardPlatformBadge: { backgroundColor: "rgba(255,255,255,0.2)", paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, alignSelf: "flex-start", marginBottom: 6 },
    cardPlatformText: { color: "#fff", fontSize: 10, fontWeight: "800" },
    cardHeaderTitle: { color: "#fff", fontSize: 17, fontWeight: "900", lineHeight: 22 },
    cardPriceArea: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "rgba(0,0,0,0.2)", padding: 12, borderRadius: 10, gap: 10 },
    cardPriceLeft: { flexDirection: "row", alignItems: "baseline", gap: 8, flexShrink: 1, minWidth: 0 },
    cardPromoPrice: { color: "#fff", fontSize: 28, fontWeight: "900" },
    cardOriginalPrice: { color: "rgba(255,255,255,0.85)", fontSize: 14, textDecorationLine: "line-through" },
    cardSaveBadge: { backgroundColor: "rgba(255,255,255,0.2)", paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, flexShrink: 0 },
    cardSaveText: { color: "#fff", fontSize: 12, fontWeight: "700" },
    cardBody: { padding: 16 },
    cardDesc: { color: "#F1F5F9", fontSize: 12, lineHeight: 18, marginBottom: 12 },
    metricsRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
    metricItem: { flex: 1, backgroundColor: "#0A1628", borderRadius: 8, padding: 8, alignItems: "center", borderWidth: 1, borderColor: "#475569" },
    metricValue: { fontSize: 15, fontWeight: "900", marginBottom: 2 },
    metricLabel: { color: "#F1F5F9", fontSize: 10 },
    cardFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12, gap: 8 },
    cardFooterLeft: { flex: 1, minWidth: 0 },
    stockInfo: { alignItems: "flex-end", flexShrink: 0 },
    stockBarOuter: { width: 80, height: 4, backgroundColor: "#475569", borderRadius: 2, overflow: "hidden", marginBottom: 3 },
    stockBarInner: { height: "100%", borderRadius: 2 },
    stockText: { color: "#F1F5F9", fontSize: 10, fontWeight: "600" },
    countdownRow: { flexDirection: "row", alignItems: "center", gap: 3 },
    countdownBlock: { backgroundColor: "#0A1628", paddingHorizontal: 6, paddingVertical: 3, borderRadius: 4, borderWidth: 1, borderColor: "#475569", minWidth: 26, alignItems: "center" },
    countdownBlockLg: { paddingHorizontal: 8, paddingVertical: 5, minWidth: 32 },
    countdownNum: { color: "#EF4444", fontSize: 12, fontWeight: "900", fontVariant: ["tabular-nums"] },
    countdownSep: { color: "#EF4444", fontSize: 12, fontWeight: "700" },
    countdownEnded: { color: "#F1F5F9", fontSize: 12, fontWeight: "600" },
    cardBuyBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingVertical: 12, borderRadius: 10 },
    cardBuyBtnText: { color: "#fff", fontSize: 14, fontWeight: "800" },

    emptyState: { alignItems: "center", paddingVertical: 60 },
    emptyText: { color: "#F1F5F9", fontSize: 16, fontWeight: "600", marginTop: 12 },
    emptySubtext: { color: "#F1F5F9", fontSize: 13, marginTop: 4 },
    whySection: { marginTop: 32, paddingHorizontal: 20, paddingVertical: 28, borderTopWidth: 1, borderTopColor: "#1E293B" },
    whySectionTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "900", textAlign: "center", marginBottom: 20 },
    whyGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
    whyItem: { width: isDesktop ? "31%" : "47%", flexGrow: 1, backgroundColor: "#1E293B", borderRadius: 14, padding: 16, borderWidth: 1, borderColor: "#475569", alignItems: "center" },
    whyIconWrap: { width: 44, height: 44, borderRadius: 22, justifyContent: "center", alignItems: "center", marginBottom: 10 },
    whyItemTitle: { color: "#FFFFFF", fontSize: 14, fontWeight: "800", marginBottom: 6, textAlign: "center" },
    whyItemDesc: { color: "#F1F5F9", fontSize: 11, lineHeight: 16, textAlign: "center" },
    bottomCta: { marginHorizontal: 20, marginTop: 24, borderRadius: 16, overflow: "hidden", borderWidth: 1, borderColor: "#A8895A" },
    bottomCtaInner: { padding: 28, alignItems: "center" },
    bottomCtaTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "900", marginTop: 12, marginBottom: 6 },
    bottomCtaDesc: { color: "#F1F5F9", fontSize: 13, marginBottom: 20, textAlign: "center", lineHeight: 20 },
    bottomCtaBtn: { backgroundColor: "#A8895A", flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 28, paddingVertical: 14, borderRadius: 24 },
    bottomCtaBtnText: { color: "#0A1628", fontSize: 15, fontWeight: "800" },

    modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.8)", justifyContent: "flex-end" },
    modalContent: { maxHeight: "92%", backgroundColor: "#1E293B", borderTopLeftRadius: 24, borderTopRightRadius: 24 },
    modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 20, borderBottomWidth: 1, borderBottomColor: "#475569" },
    modalTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "800", flex: 1, marginRight: 12 },
    modalBody: { padding: 20 },
    modalCover: { width: "100%", height: 200, borderRadius: 12, marginBottom: 16 },
    modalPriceBox: { padding: 16, borderRadius: 12, marginBottom: 16 },
    modalPriceRow: { flexDirection: "row", alignItems: "baseline", gap: 10, flexWrap: "wrap" },
    modalPromoPrice: { color: "#fff", fontSize: 32, fontWeight: "900" },
    modalOriginalPrice: { color: "rgba(255,255,255,0.9)", fontSize: 16, textDecorationLine: "line-through" },
    modalSaveBadge: { backgroundColor: "rgba(255,255,255,0.2)", paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
    modalSaveText: { color: "#fff", fontSize: 12, fontWeight: "700" },
    modalTags: { flexDirection: "row", gap: 8, marginBottom: 16, flexWrap: "wrap" },
    modalTag: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 },
    modalTagText: { color: "#FFFFFF", fontSize: 12, fontWeight: "700" },
    modalDesc: { color: "#CBD5E1", fontSize: 14, lineHeight: 22, marginBottom: 16 },
    modalDetailSection: { marginBottom: 16 },
    modalSectionTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "800", marginBottom: 10 },
    modalDetailContent: { color: "#F1F5F9", fontSize: 13, lineHeight: 22 },
    modalGallerySection: { marginBottom: 16 },
    galleryThumb: { width: 120, height: 80, borderRadius: 8, marginRight: 10 },
    buyProcessSection: { marginBottom: 20 },
    buyStep: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 10 },
    buyStepNum: { width: 28, height: 28, borderRadius: 14, backgroundColor: "#A8895A", justifyContent: "center", alignItems: "center" },
    buyStepNumText: { color: "#0A1628", fontSize: 14, fontWeight: "800" },
    buyStepText: { color: "#CBD5E1", fontSize: 13, flex: 1 },
    buyBtn: { marginBottom: 12 },
    buyBtnGradient: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingVertical: 15, borderRadius: 12 },
    buyBtnText: { color: "#fff", fontSize: 17, fontWeight: "900" },
    safetyNote: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 12 },
    safetyNoteText: { color: "#F1F5F9", fontSize: 12 },
    contactModal: { marginHorizontal: 20, borderRadius: 20, overflow: "hidden" },
    contactModalInner: { padding: 24 },
    contactHeader: { alignItems: "center", marginBottom: 20 },
    contactIconWrap: { width: 56, height: 56, borderRadius: 28, backgroundColor: "rgba(217,119,6,0.15)", justifyContent: "center", alignItems: "center", marginBottom: 12 },
    contactTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "800", marginBottom: 6 },
    contactDesc: { color: "#F1F5F9", fontSize: 13, textAlign: "center" },
    contactMethods: { gap: 10, marginBottom: 16 },
    contactMethod: { flexDirection: "row", alignItems: "center", gap: 14, padding: 16, borderRadius: 12 },
    contactMethodLabel: { color: "rgba(255,255,255,0.7)", fontSize: 12 },
    contactMethodValue: { color: "#fff", fontSize: 16, fontWeight: "700" },
    payMethods: { marginBottom: 16 },
    payMethodsTitle: { color: "#F1F5F9", fontSize: 12, marginBottom: 8, textAlign: "center" },
    payMethodsRow: { flexDirection: "row", justifyContent: "center", gap: 8, flexWrap: "wrap" },
    payMethodChip: { backgroundColor: "#475569", paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8 },
    payMethodChipText: { color: "#FFFFFF", fontSize: 12, fontWeight: "600" },
    contactCloseBtn: { alignItems: "center", paddingVertical: 12 },
    contactCloseBtnText: { color: "#F1F5F9", fontSize: 14 },
    galleryModal: { flex: 1, backgroundColor: "rgba(0,0,0,0.95)", justifyContent: "center", alignItems: "center" },
    galleryClose: { position: "absolute", top: 50, right: 20, zIndex: 10 },
    galleryFullImage: { width: screenWidth - 40, height: screenWidth - 40, borderRadius: 8 },
    galleryNav: { flexDirection: "row", alignItems: "center", gap: 24, marginTop: 20 },
    galleryCounter: { color: "#fff", fontSize: 14 },
  });
}

export type PromoStyles = ReturnType<typeof createPromoStyles>;
