import type { HomeStrategy } from "./types";

export const LOCAL_PREVIEW_STRATEGIES: HomeStrategy[] = [
  {
    id: -101,
    title: "XAU Alpha Source Pro",
    platform: "MT5",
    totalReturn: "168.40",
    winRate: "71.20",
    price: "699.00",
    originalPrice: "1299.00",
    isFree: false,
    downloadCount: 1260,
    virtualDownloads: 420,
    coverImage: null,
    pairs: "XAUUSD",
    viewCount: 8200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9),
    tags: "黄金,趋势",
    productType: "ea",
    isFeatured: true,
    isCurated: true,
    featuredLink: null,
    saleMode: "inquiry",
    dataStatus: "referenced",
  },
  {
    id: -102,
    title: "London Scalper Desk",
    platform: "MT4",
    totalReturn: "96.80",
    winRate: "74.60",
    price: "399.00",
    originalPrice: "699.00",
    isFree: false,
    downloadCount: 880,
    virtualDownloads: 210,
    coverImage: null,
    pairs: "EURUSD,GBPUSD",
    viewCount: 5100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 28),
    tags: "剥头皮,短线",
    productType: "ea",
    isFeatured: false,
    isCurated: true,
    featuredLink: null,
    saleMode: "inquiry",
    dataStatus: "estimated",
  },
  {
    id: -103,
    title: "Grid Risk Controller",
    platform: "MT5",
    totalReturn: "132.50",
    winRate: "68.90",
    price: "599.00",
    originalPrice: "999.00",
    isFree: false,
    downloadCount: 720,
    virtualDownloads: 160,
    coverImage: null,
    pairs: "XAUUSD,EURUSD",
    viewCount: 4300,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    tags: "网格,风控",
    productType: "tool",
    isFeatured: false,
    isCurated: true,
    featuredLink: null,
    saleMode: "inquiry",
    dataStatus: "estimated",
  },
  {
    id: -104,
    title: "Institutional Trend Filter",
    platform: "MT4",
    totalReturn: "84.30",
    winRate: "76.10",
    price: "299.00",
    originalPrice: null,
    isFree: false,
    downloadCount: 640,
    virtualDownloads: 132,
    coverImage: null,
    pairs: "XAUUSD,US30",
    viewCount: 3800,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
    tags: "指标,趋势",
    productType: "indicator",
    isFeatured: false,
    isCurated: false,
    featuredLink: null,
    saleMode: "inquiry",
    dataStatus: "estimated",
  },
  {
    id: -105,
    title: "Prop Firm Guard EA",
    platform: "MT5",
    totalReturn: "58.70",
    winRate: "69.40",
    price: "0.00",
    originalPrice: null,
    isFree: false,
    downloadCount: 1540,
    virtualDownloads: 360,
    coverImage: null,
    pairs: "EURUSD,USDJPY",
    viewCount: 6200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
    tags: "风控,prop",
    productType: "ea",
    isFeatured: false,
    isCurated: true,
    featuredLink: null,
    saleMode: "inquiry",
    dataStatus: "referenced",
  },
  {
    id: -106,
    title: "Multi Asset Hedge Core",
    platform: "MT4",
    totalReturn: "121.90",
    winRate: "66.80",
    price: "899.00",
    originalPrice: "1599.00",
    isFree: false,
    downloadCount: 590,
    virtualDownloads: 118,
    coverImage: null,
    pairs: "XAUUSD,US30,BTCUSD",
    viewCount: 3500,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120),
    tags: "对冲,多资产",
    productType: "ea",
    isFeatured: false,
    isCurated: false,
    featuredLink: null,
    saleMode: "inquiry",
    dataStatus: "estimated",
  },
];
