import { Platform, StyleSheet } from "react-native";

export const strategyInventoryStyles = StyleSheet.create({
  pageShell: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 14,
    paddingTop: 14,
  },
  pageShellDesktop: {
    maxWidth: 1360,
    alignSelf: "center",
    paddingHorizontal: 22,
    paddingTop: 18,
  },
  controlPanel: {
    padding: 14,
    borderWidth: 1,
    borderRadius: 6,
    marginBottom: 10,
    backgroundColor: "rgba(9,15,28,0.86)",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  headingBlock: {
    flex: 1,
    minWidth: 0,
  },
  kicker: {
    color: "#D8BC83",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "900",
    marginBottom: 3,
  },
  title: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "900",
  },
  subtitle: {
    fontSize: 11,
    lineHeight: 17,
    marginTop: 3,
  },
  addButton: {
    minHeight: 38,
    borderRadius: 5,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    flexShrink: 0,
  },
  addButtonText: {
    color: "#07101D",
    fontSize: 13,
    fontWeight: "800",
  },
  toolbar: {
    marginTop: 13,
    gap: 9,
  },
  toolbarDesktop: {
    flexDirection: "row",
    alignItems: "center",
  },
  searchBox: {
    minHeight: 40,
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 8,
    fontSize: 13,
    lineHeight: 18,
    ...(Platform.OS === "web" ? ({ outlineStyle: "none" } as any) : {}),
  },
  clearSearchButton: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  filterButton: {
    minHeight: 40,
    borderRadius: 5,
    borderWidth: 1,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: "700",
  },
  filterCount: {
    fontSize: 12,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  resultRow: {
    minHeight: 28,
    marginTop: 11,
    paddingTop: 9,
    borderTopWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  resultText: {
    fontSize: 11,
    fontWeight: "600",
  },
  resultCount: {
    fontSize: 12,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  listPanel: {
    flex: 1,
    minHeight: 0,
  },
  listContent: {
    paddingBottom: 34,
  },
  listContentMobile: {
    gap: 8,
  },
  tableHeader: {
    minHeight: 38,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    backgroundColor: "#0A1322",
  },
  columnLabel: {
    fontSize: 10,
    fontWeight: "900",
  },
  tableRow: {
    minHeight: 70,
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
  },
  strategyColumn: {
    flex: 1,
    minWidth: 220,
    paddingRight: 16,
  },
  titleButton: {
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
    marginBottom: 4,
  },
  itemId: {
    width: 42,
    flexShrink: 0,
    fontSize: 10,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  itemTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
  },
  detailText: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "500",
  },
  platformColumn: {
    width: 68,
    flexShrink: 0,
  },
  platformText: {
    fontSize: 11,
    fontWeight: "900",
  },
  statusColumn: {
    width: 86,
    flexShrink: 0,
  },
  statusBadge: {
    alignSelf: "flex-start",
    borderRadius: 4,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  statusText: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "800",
  },
  metricsColumn: {
    width: 224,
    flexShrink: 0,
    flexDirection: "row",
    gap: 14,
  },
  metricCell: {
    minWidth: 54,
  },
  metricLabel: {
    fontSize: 9,
    lineHeight: 12,
    fontWeight: "700",
    marginBottom: 3,
  },
  metricValue: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
  },
  actionsDesktop: {
    width: 220,
    flexShrink: 0,
    marginTop: 0,
  },
  actionButton: {
    minHeight: 32,
    borderRadius: 4,
    paddingHorizontal: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  editButton: {
    backgroundColor: "rgba(216,188,131,0.12)",
    borderWidth: 1,
    borderColor: "rgba(216,188,131,0.30)",
  },
  editButtonText: {
    color: "#D8BC83",
    fontSize: 11,
    fontWeight: "800",
  },
  backtestButton: {
    backgroundColor: "rgba(52,211,153,0.08)",
  },
  deleteButton: {
    backgroundColor: "rgba(248,113,113,0.08)",
  },
  actionButtonText: {
    fontSize: 11,
    fontWeight: "800",
  },
  mobileCard: {
    borderWidth: 1,
    borderRadius: 6,
    padding: 11,
  },
  mobileTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 5,
  },
  mobileTitleButton: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  mobileTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
  },
  mobileMetaRow: {
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
  },
  metricInline: {
    fontSize: 11,
    fontWeight: "600",
  },
  emptyState: {
    paddingVertical: 54,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: "800",
    marginTop: 10,
  },
  emptyText: {
    fontSize: 11,
    lineHeight: 17,
    marginTop: 4,
  },
});
