import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import { strategies } from "../drizzle/schema";
import * as dotenv from "dotenv";

dotenv.config();

const mockStrategies = [
  {
    title: "Golden Scalper Pro",
    description: "专注于黄金市场的高频剥头皮策略,采用动态止损和智能仓位管理,适合M5-M15时间周期。经过3年实盘验证,稳定盈利。",
    platform: "MT4" as const,
    pairs: "XAUUSD",
    timeframe: "M5, M15",
    coverImage: "/assets/ea-covers/Van85YG2HsVk.png",
    totalReturn: "127.50",
    maxDrawdown: "8.30",
    sharpeRatio: "2.45",
    winRate: "68.50",
    downloadUrl: "https://example.com/download/golden-scalper-pro.ex4",
    price: "299.00",
    isFree: false,
    telegramGroup: "https://t.me/goldenscalper",
    qqGroup: "123456789",
    status: "published" as const,
  },
  {
    title: "EUR/USD Trend Master",
    description: "基于趋势跟踪的欧美货币对策略,结合多重时间框架分析和动量指标,捕捉中长期趋势。月均收益稳定在5-8%。",
    platform: "MT5" as const,
    pairs: "EURUSD",
    timeframe: "H1, H4",
    coverImage: "/assets/ea-covers/ARhiBiZCL4Zq.jpg",
    totalReturn: "89.20",
    maxDrawdown: "12.50",
    sharpeRatio: "1.85",
    winRate: "62.30",
    downloadUrl: "https://example.com/download/eurusd-trend-master.ex5",
    price: "199.00",
    isFree: false,
    telegramGroup: "https://t.me/eurusdtrend",
    qqGroup: "987654321",
    status: "published" as const,
  },
  {
    title: "Multi-Pair Grid EA",
    description: "多货币对网格交易系统,同时交易EURUSD、GBPUSD、USDJPY等主流货币对,分散风险,稳定收益。支持自定义网格间距。",
    platform: "MT4" as const,
    pairs: "EURUSD, GBPUSD, USDJPY, AUDUSD",
    timeframe: "H1",
    coverImage: "/assets/ea-covers/4YsQYBJh9alU.png",
    totalReturn: "156.80",
    maxDrawdown: "15.20",
    sharpeRatio: "2.10",
    winRate: "71.40",
    downloadUrl: "https://example.com/download/multi-pair-grid.ex4",
    price: "399.00",
    isFree: false,
    telegramGroup: "https://t.me/multipairgrid",
    qqGroup: "456789123",
    status: "published" as const,
  },
  {
    title: "Smart Breakout Hunter",
    description: "突破交易策略,识别关键支撑阻力位并在突破时入场。配备智能过滤器减少假突破,适合波动性较大的市场环境。",
    platform: "MT5" as const,
    pairs: "GBPUSD, EURJPY",
    timeframe: "H4, D1",
    coverImage: "/assets/ea-covers/gT5WWDuxFqaE.png",
    totalReturn: "94.30",
    maxDrawdown: "10.80",
    sharpeRatio: "1.95",
    winRate: "59.20",
    downloadUrl: "https://example.com/download/smart-breakout.ex5",
    price: "249.00",
    isFree: false,
    telegramGroup: "https://t.me/smartbreakout",
    qqGroup: "789123456",
    status: "published" as const,
  },
  {
    title: "Night Scalper",
    description: "专为亚洲时段设计的剥头皮策略,利用低波动性和窄幅震荡获利。风险控制严格,适合保守型交易者。",
    platform: "MT4" as const,
    pairs: "USDJPY, AUDJPY",
    timeframe: "M15, M30",
    coverImage: "/assets/ea-covers/EfSE5PGWwOi4.png",
    totalReturn: "72.60",
    maxDrawdown: "6.50",
    sharpeRatio: "2.30",
    winRate: "74.10",
    downloadUrl: "https://example.com/download/night-scalper.ex4",
    price: "179.00",
    isFree: false,
    telegramGroup: "https://t.me/nightscalper",
    qqGroup: "321654987",
    status: "published" as const,
  },
  {
    title: "Fibonacci Retracement Pro",
    description: "基于斐波那契回撤理论的交易系统,自动识别关键回撤位并在最佳点位入场。结合价格行为分析,提高胜率。",
    platform: "MT5" as const,
    pairs: "EURUSD, GBPUSD, XAUUSD",
    timeframe: "H1, H4",
    coverImage: "/assets/ea-covers/alnTY1KahE37.jpg",
    totalReturn: "108.40",
    maxDrawdown: "11.20",
    sharpeRatio: "2.05",
    winRate: "65.80",
    downloadUrl: "https://example.com/download/fibonacci-pro.ex5",
    price: "279.00",
    isFree: false,
    telegramGroup: "https://t.me/fibonaccipro",
    qqGroup: "654987321",
    status: "published" as const,
  },
  {
    title: "RSI Divergence Master",
    description: "利用RSI背离信号捕捉趋势反转点,配合MACD确认入场时机。适合中短期交易,月均交易次数20-30次。",
    platform: "MT4" as const,
    pairs: "EURUSD, GBPUSD",
    timeframe: "H1",
    coverImage: "/assets/ea-covers/vyjCdLR0sBkW.png",
    totalReturn: "83.70",
    maxDrawdown: "9.40",
    sharpeRatio: "1.90",
    winRate: "63.50",
    downloadUrl: "https://example.com/download/rsi-divergence.ex4",
    price: "0.00",
    isFree: true,
    telegramGroup: "https://t.me/rsidivergence",
    qqGroup: "147258369",
    status: "published" as const,
  },
  {
    title: "Martingale Gold EA",
    description: "黄金市场马丁格尔策略,采用改良版资金管理,设置最大加仓次数和止损保护。高风险高收益,需谨慎使用。",
    platform: "MT5" as const,
    pairs: "XAUUSD",
    timeframe: "M5, M15",
    coverImage: "/assets/ea-covers/Van85YG2HsVk.png",
    totalReturn: "215.30",
    maxDrawdown: "28.60",
    sharpeRatio: "1.45",
    winRate: "55.20",
    downloadUrl: "https://example.com/download/martingale-gold.ex5",
    price: "349.00",
    isFree: false,
    telegramGroup: "https://t.me/martingalegold",
    qqGroup: "258369147",
    status: "published" as const,
  },
  {
    title: "London Breakout Strategy",
    description: "专注于伦敦开盘时段的突破策略,利用欧洲市场开盘带来的高波动性获利。配备时间过滤器,仅在最佳时段交易。",
    platform: "MT4" as const,
    pairs: "GBPUSD, EURGBP",
    timeframe: "M15, M30",
    coverImage: "/assets/ea-covers/4YsQYBJh9alU.png",
    totalReturn: "96.50",
    maxDrawdown: "10.30",
    sharpeRatio: "2.00",
    winRate: "66.70",
    downloadUrl: "https://example.com/download/london-breakout.ex4",
    price: "0.00",
    isFree: true,
    telegramGroup: "https://t.me/londonbreakout",
    qqGroup: "369147258",
    status: "published" as const,
  },
  {
    title: "AI Trend Predictor",
    description: "基于机器学习算法的趋势预测系统,分析历史数据和市场情绪,预测未来价格走势。需要较高配置VPS运行。",
    platform: "MT5" as const,
    pairs: "EURUSD, GBPUSD, USDJPY, XAUUSD",
    timeframe: "H1, H4, D1",
    coverImage: "/assets/ea-covers/gT5WWDuxFqaE.png",
    totalReturn: "142.80",
    maxDrawdown: "13.70",
    sharpeRatio: "2.25",
    winRate: "69.30",
    downloadUrl: "https://example.com/download/ai-trend-predictor.ex5",
    price: "599.00",
    isFree: false,
    telegramGroup: "https://t.me/aitrendpredictor",
    qqGroup: "741852963",
    status: "published" as const,
  },
  {
    title: "Conservative Swing Trader",
    description: "保守型波段交易策略,持仓周期3-7天,追求稳定收益。风险控制严格,每笔交易风险不超过账户的1%。",
    platform: "MT4" as const,
    pairs: "EURUSD, AUDUSD",
    timeframe: "D1",
    coverImage: "/assets/ea-covers/alnTY1KahE37.jpg",
    totalReturn: "58.40",
    maxDrawdown: "5.80",
    sharpeRatio: "2.50",
    winRate: "72.60",
    downloadUrl: "https://example.com/download/conservative-swing.ex4",
    price: "149.00",
    isFree: false,
    telegramGroup: "https://t.me/conservativeswing",
    qqGroup: "852963741",
    status: "published" as const,
  },
  {
    title: "Volatility Breakout System",
    description: "波动率突破系统,在市场波动率达到特定阈值时入场。适合重要经济数据发布时段,捕捉大行情。",
    platform: "MT5" as const,
    pairs: "EURUSD, GBPUSD, USDJPY",
    timeframe: "M5, M15",
    coverImage: "/assets/ea-covers/EfSE5PGWwOi4.png",
    totalReturn: "118.90",
    maxDrawdown: "14.50",
    sharpeRatio: "1.80",
    winRate: "61.40",
    downloadUrl: "https://example.com/download/volatility-breakout.ex5",
    price: "269.00",
    isFree: false,
    telegramGroup: "https://t.me/volatilitybreakout",
    qqGroup: "963741852",
    status: "published" as const,
  },
];

async function seedStrategies() {
  console.log("开始添加虚拟EA策略数据...");

  const connection = await mysql.createConnection({
    host: process.env.DATABASE_HOST,
    user: process.env.DATABASE_USER,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_NAME,
  });

  const db = drizzle(connection);

  try {
    for (const strategy of mockStrategies) {
      await db.insert(strategies).values(strategy);
      console.log(`✓ 已添加: ${strategy.title}`);
    }

    console.log(`\n成功添加 ${mockStrategies.length} 个虚拟EA策略!`);
  } catch (error) {
    console.error("添加数据时出错:", error);
  } finally {
    await connection.end();
  }
}

seedStrategies();
