import { StyleSheet } from "react-native";
import { V2, V2_LAYOUT } from "@/components/v2/tokens";

export const detailStyles = StyleSheet.create({
  scroll: { flex: 1, backgroundColor: V2.background },
  scrollContent: { paddingBottom: 48 },
  page: {
    width: "100%",
    maxWidth: V2_LAYOUT.maxWidth,
    alignSelf: "center",
    paddingHorizontal: V2_LAYOUT.pagePaddingDesktop,
    paddingTop: 12,
    gap: 24,
  },
  pageMobile: {
    paddingHorizontal: V2_LAYOUT.pagePaddingMobile,
    paddingTop: 8,
    gap: 20,
  },
  topline: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: V2.border,
  },
  backButton: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  backText: { color: V2.textMuted, fontSize: 10, fontWeight: "800" },
  formula: { color: V2.textDim, fontSize: 9, fontWeight: "800" },
  hero: {
    minHeight: 318,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 24,
  },
  heroNarrow: { minHeight: 0, flexDirection: "column", gap: 18 },
  artworkWrap: {
    flex: 0.88,
    minWidth: 0,
    minHeight: 278,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 6,
    overflow: "hidden",
    position: "relative",
    backgroundColor: V2.surfaceMuted,
  },
  artwork: { width: "100%", height: "100%" },
  artworkRail: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
  },
  artworkStatus: { position: "absolute", top: 12, right: 12 },
  heroCopy: { flex: 1.12, minWidth: 0, justifyContent: "center" },
  identity: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  identityCopy: { flex: 1, minWidth: 0 },
  slotLabel: { color: V2.gold, fontSize: 9, fontWeight: "900" },
  title: {
    marginTop: 4,
    color: V2.text,
    fontSize: 31,
    lineHeight: 38,
    fontWeight: "900",
  },
  titleMobile: { fontSize: 27, lineHeight: 33 },
  version: { marginTop: 3, color: V2.gold, fontSize: 10, fontWeight: "900" },
  updatedAt: { color: V2.textDim, fontSize: 9, textAlign: "right" },
  tagline: {
    marginTop: 11,
    color: V2.text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "800",
  },
  description: {
    marginTop: 5,
    color: V2.textMuted,
    fontSize: 11,
    lineHeight: 18,
    maxWidth: 650,
  },
  metrics: {
    marginTop: 14,
    minHeight: 82,
    flexDirection: "row",
    flexWrap: "wrap",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: V2.border,
  },
  metric: {
    width: "33.33%",
    minWidth: 118,
    justifyContent: "center",
    gap: 2,
    paddingVertical: 7,
    paddingRight: 8,
  },
  metricLabel: { color: V2.textDim, fontSize: 8 },
  metricValue: { fontSize: 12, lineHeight: 16, fontWeight: "900" },
  actions: { marginTop: 14, flexDirection: "row", gap: 8 },
  actionsMobile: { flexDirection: "column" },
  primaryButton: {
    minHeight: 40,
    paddingHorizontal: 13,
    borderRadius: 4,
    backgroundColor: V2.gold,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  primaryButtonText: { color: V2.background, fontSize: 11, fontWeight: "900" },
  secondaryButton: {
    minHeight: 40,
    paddingHorizontal: 13,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: V2.borderStrong,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  secondaryButtonText: { color: V2.text, fontSize: 10, fontWeight: "800" },
  fitBar: {
    minHeight: 70,
    paddingVertical: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: V2.border,
  },
  fitItem: {
    minWidth: 130,
    flex: 1,
    paddingRight: 14,
    justifyContent: "center",
    gap: 3,
  },
  fitItemWide: { flex: 1.7 },
  fitLabel: { color: V2.textDim, fontSize: 8 },
  fitValue: { color: V2.text, fontSize: 10, lineHeight: 15, fontWeight: "800" },
  performance: { flexDirection: "row", alignItems: "stretch", gap: 12 },
  performanceNarrow: { flexDirection: "column" },
  chartPanel: {
    flex: 1,
    minWidth: 0,
    padding: 16,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 6,
    backgroundColor: V2.backgroundRaised,
  },
  chartHeading: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 16,
  },
  chartHeadingMobile: { alignItems: "flex-start", flexDirection: "column" },
  sectionEyebrow: { color: V2.gold, fontSize: 9, fontWeight: "900" },
  sectionTitle: {
    marginTop: 2,
    color: V2.text,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: "900",
  },
  rangeControl: {
    padding: 3,
    flexDirection: "row",
    gap: 2,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 4,
    backgroundColor: V2.surfaceMuted,
  },
  rangeButton: {
    minWidth: 44,
    minHeight: 29,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 2,
  },
  rangeButtonActive: { backgroundColor: V2.surface },
  rangeText: { color: V2.textMuted, fontSize: 9, fontWeight: "800" },
  rangeTextActive: { color: V2.gold },
  chartTopline: {
    minHeight: 48,
    paddingTop: 12,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  chartMeta: { color: V2.textMuted, fontSize: 9 },
  chartEquity: {
    marginTop: 3,
    color: V2.text,
    fontSize: 16,
    fontWeight: "900",
  },
  snapshot: {
    width: 320,
    flexShrink: 0,
    padding: 16,
    borderWidth: 1,
    borderColor: V2.border,
    borderRadius: 6,
    backgroundColor: V2.surfaceMuted,
    gap: 12,
  },
  snapshotTitle: {
    marginTop: 2,
    color: V2.text,
    fontSize: 18,
    fontWeight: "900",
  },
  snapshotRows: { borderTopWidth: 1, borderTopColor: V2.border },
  snapshotRow: {
    minHeight: 40,
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: V2.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  snapshotLabel: { color: V2.textDim, fontSize: 9 },
  snapshotValue: {
    color: V2.text,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "right",
  },
  snapshotHint: { color: V2.textMuted, fontSize: 9, lineHeight: 15 },
  activitySection: { gap: 0 },
  tabs: {
    minHeight: 46,
    flexDirection: "row",
    gap: 2,
    borderBottomWidth: 1,
    borderBottomColor: V2.border,
  },
  tab: {
    minHeight: 46,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActive: { borderBottomColor: V2.gold },
  tabText: { color: V2.textMuted, fontSize: 10, fontWeight: "700" },
  tabTextActive: { color: V2.text, fontWeight: "900" },
  table: { borderTopWidth: 1, borderTopColor: V2.border },
  tableRow: {
    minHeight: 54,
    paddingHorizontal: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: V2.border,
  },
  tableRowMobile: {
    minHeight: 0,
    paddingVertical: 13,
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  tableHeader: { minHeight: 38, backgroundColor: V2.surfaceMuted },
  cell: { minWidth: 74, fontSize: 10, lineHeight: 15 },
  empty: {
    minHeight: 150,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: V2.border,
  },
  emptyText: { color: V2.textMuted, fontSize: 10 },
  bottomNotice: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: V2.border,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
  },
  bottomNoticeText: {
    flex: 1,
    color: V2.textMuted,
    fontSize: 10,
    lineHeight: 16,
  },
  pressed: { opacity: 0.72 },
});
